### ISSUE TITLE
TODO 残作業

### ISSUE THREAD

**Issue by uk-taniyama** [uk-taniyama/chartjs-gauge#2]
- [x] add docs for npm-package.
- [x] add cjs, esm
- [x] github-pages docsの見直し。

**Comment by uk-taniyama** [comment]
chart.jsのinterfaceにリンクを張りたい。

**Comment by uk-taniyama** [comment]
lavelValueのcolorとneedleのcolorのデフォルトが残念.......
＃黒と黒になっている.......
